// <auto-generated />
using System;
using ContactManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210108174745_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactGroup")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthdate = new DateTime(1997, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactGroup = "Friends",
                            CreatedAt = new DateTime(2021, 1, 8, 10, 47, 44, 875, DateTimeKind.Local).AddTicks(1664),
                            Description = "Tallest, strongest, coolest, and most handsome developer I've ever seen",
                            Favorite = true,
                            Name = "Nathan Benson",
                            UpdatedAt = new DateTime(2021, 1, 8, 10, 47, 44, 877, DateTimeKind.Local).AddTicks(3619)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
