// <auto-generated />
using ContactManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthdate = "March 28, 1997",
                            ContactGroup = "Friends",
                            CreatedAt = "1/8/2021 12:57:54 PM",
                            Description = "Tallest, strongest, coolest, and most handsome developer I've ever seen",
                            Favorite = true,
                            Name = "Nathan Benson",
                            UpdatedAt = "1/8/2021 12:57:54 PM"
                        },
                        new
                        {
                            Id = 2L,
                            Birthdate = "November 3, 1994",
                            ContactGroup = "Friends",
                            CreatedAt = "1/8/2021 12:57:54 PM",
                            Description = "Nate's beautiful wife",
                            Favorite = true,
                            Name = "Janessa Benson",
                            UpdatedAt = "1/8/2021 12:57:54 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
